### ISSUE TITLE
SwinLSTM_D method

### ISSUE THREAD

**Issue by IsmailBData** [chengtan9907/OpenSTL#100]
my custom_training_config is :

custom_training_config = {
    'pre_seq_length': pre_seq_length,
    'aft_seq_length': aft_seq_length,
    'total_length': pre_seq_length + aft_seq_length,
    'batch_size': batch_size,
    'val_batch_size': batch_size,
    'epoch': 50,
    'lr': 0.001,
    'metrics': ['mse', 'mae'],

    'ex_name': 'custom_exp',
    'dataname': 'custom',
    'in_shape': [10, 3, 100, 100],
}

what should be the custom_model_config where the method is SwinLSTM_D.

**Comment by chengtan9907** [comment]
I think you may refer to the default config file of Moving MNIST: [configs/mmnist/SwinLSTM-D.py](https://github.com/chengtan9907/OpenSTL/blob/OpenSTL-Lightning/configs/mmnist/SwinLSTM-D.py)

**Comment by chengtan9907** [comment]
I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.
