### ISSUE TITLE
mask_true arguments

### ISSUE THREAD

**Issue by abdo-RG** [chengtan9907/OpenSTL#101]
What mask_true stand for in forword function '[openstl/models/mim_model.py](https://github.com/chengtan9907/OpenSTL/blob/d7bb9e172c6ab240c3bb60f1458e4f2ff6e94ec7/openstl/models/mim_model.py#L51)'

**Comment by chengtan9907** [comment]
It is the mask for schedule sampling. I would like to suggest you to refer PredRNNv2 ([PredRNN: A Recurrent Neural Network for Spatiotemporal Predictive Learning](https://arxiv.org/pdf/2103.09504.pdf)). See Fig.5 on page 7.

**Comment by IsmailBData** [comment]
how can i specify it in my own dataset

**Comment by chengtan9907** [comment]
I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.
