### ISSUE TITLE
training log 

### ISSUE THREAD

**Issue by IsmailBData** [chengtan9907/OpenSTL#102]
what if i wanted to display my log for ConvLSTM like this : 

2024-01-24 20:24:14,731 - vali mse:101.0427, mae:236.4133, ssim:0.6893, psnr:34.3820
2024-01-24 20:24:14,733 - Epoch: 5 | Train Loss: 0.0249 Vali Loss: 0.0247

because all what i get is this Train Loss: 0.0249 Vali Loss: 0.0247.

**Comment by chengtan9907** [comment]
The 'valid mse' refers to the mean squared error at the frame level, while the 'Valid Loss' represents the mean squared error at the pixel level. Based on the information you provided, it seems like you are training the Moving MNIST dataset. If I understand correctly, the calculation 0.0247 * 64 * 64 results in a value of approximately 101.

**Comment by chengtan9907** [comment]
If you find this repository helpful, I kindly request you to consider giving it a star. Your support and feedback are greatly appreciated. Thank you!

**Comment by IsmailBData** [comment]
my question is how to display my log like the provided one above not judt like this: Train Loss: 0.0249 Vali Loss: 0.0247.

**Comment by chengtan9907** [comment]
Please use the older branch: [OpenSTL v0.3.0](https://github.com/chengtan9907/OpenSTL/tree/OpenSTLv0.3.0)

**Comment by easewkx** [comment]
> 请使用较旧的分支：[OpenSTL v0.3.0](https://github.com/chengtan9907/OpenSTL/tree/OpenSTLv0.3.0)

请问我复现openstlv0.3.0的时候为什么一直报这个错
![image](https://github.com/chengtan9907/OpenSTL/assets/104662881/b08d9510-5a9b-4199-b0be-c0ebfca39118)
