### ISSUE TITLE
setting of mask_true argument

### ISSUE THREAD

**Issue by IsmailBData** [chengtan9907/OpenSTL#104]
i want to do my own training loop using convLSTM but i couldn't because i do not know how can i specify the mask true argument in the forward method????

My loop unfortunately failed because of it.

`

    import torch
    import torch.nn as nn
   
    class ConvLSTMCell(nn.Module):
    
        def __init__(self, in_channel, num_hidden, height, width, filter_size, stride, layer_norm):
            super(ConvLSTMCell, self).__init__()
    
            self.num_hidden = num_hidden
            self.padding = filter_size // 2
            self._forget_bias = 1.0
            if layer_norm:
                self.conv_x = nn.Sequential(
                    nn.Conv2d(in_channel, num_hidden * 4, kernel_size=filter_size,
                              stride=stride, padding=self.padding, bias=False),
                    nn.LayerNorm([num_hidden * 4, height, width])
                )
                self.conv_h = nn.Sequential(
                    nn.Conv2d(num_hidden, num_hidden * 4, kernel_size=filter_size,
                              stride=stride, padding=self.padding, bias=False),
                    nn.LayerNorm([num_hidden * 4, height, width])
                )
                self.conv_o = nn.Sequential(
                    nn.Conv2d(num_hidden * 2, num_hidden, kernel_size=filter_size,
                              stride=stride, padding=self.padding, bias=False),
                    nn.LayerNorm([num_hidden, height, width])
                )
            else:
                self.conv_x = nn.Sequential(
                    nn.Conv2d(in_channel, num_hidden * 4, kernel_size=filter_size,
                              stride=stride, padding=self.padding, bias=False),
                )
                self.conv_h = nn.Sequential(
                    nn.Conv2d(num_hidden, num_hidden * 4, kernel_size=filter_size,
                              stride=stride, padding=self.padding, bias=False),
                )
                self.conv_o = nn.Sequential(
                    nn.Conv2d(num_hidden * 2, num_hidden, kernel_size=filter_size,
                              stride=stride, padding=self.padding, bias=False),
                )
            self.conv_last = nn.Conv2d(num_hidden * 2, num_hidden, kernel_size=1,
                                       stride=1, padding=0, bias=False)
    
        def forward(self, x_t, h_t, c_t):
            x_concat = self.conv_x(x_t)
            h_concat = self.conv_h(h_t)
            i_x, f_x, g_x, o_x = torch.split(x_concat, self.num_hidden, dim=1)
            i_h, f_h, g_h, o_h = torch.split(h_concat, self.num_hidden, dim=1)
    
            i_t = torch.sigmoid(i_x + i_h)
            f_t = torch.sigmoid(f_x + f_h)
            g_t = torch.tanh(g_x + g_h)
    
            c_new = f_t * c_t + i_t * g_t
            o_t = torch.sigmoid(o_x + o_h)
            h_new = o_t * torch.tanh(c_new)
            return h_new, c_new
        
    
    
    pre_seq_length = 10
    aft_seq_length = 1    
    configs = {
        'pre_seq_length': pre_seq_length,
        'aft_seq_length': aft_seq_length,
        'patch_size': 4,
        'in_shape': [10, 3, 100, 100],
        'filter_size' : 5,
        'stride' :1,
        'layer_norm' :0,
    }
    
    
    
    class ConvLSTM_Model(nn.Module):
        r"""ConvLSTM Model
    
        Implementation of `Convolutional LSTM Network: A Machine Learning Approach
        for Precipitation Nowcasting <https://arxiv.org/abs/1506.04214>`_.
    
        """
    
        def __init__(self, num_layers, num_hidden, configs, **kwargs):
            super(ConvLSTM_Model, self).__init__()
            T, C, H, W = configs.in_shape
    
            self.configs = configs
            self.frame_channel = configs.patch_size * configs.patch_size * C
            self.num_layers = num_layers
            self.num_hidden = num_hidden
            cell_list = []
    
            height = H // configs.patch_size
            width = W // configs.patch_size
            self.MSE_criterion = nn.MSELoss()
    
            for i in range(num_layers):
                in_channel = self.frame_channel if i == 0 else num_hidden[i - 1]
                cell_list.append(
                    ConvLSTMCell(in_channel, num_hidden[i], height, width, configs.filter_size,
                                           configs.stride, configs.layer_norm)
                )
            self.cell_list = nn.ModuleList(cell_list)
            self.conv_last = nn.Conv2d(num_hidden[num_layers - 1], self.frame_channel,
                                       kernel_size=1, stride=1, padding=0, bias=False)
    
        def forward(self, frames_tensor, mask_true, **kwargs):
            # [batch, length, height, width, channel] -> [batch, length, channel, height, width]
            device = frames_tensor.device
            frames = frames_tensor.permute(0, 1, 4, 2, 3).contiguous()
            mask_true = mask_true.permute(0, 1, 4, 2, 3).contiguous()
    
            batch = frames.shape[0]
            height = frames.shape[3]
            width = frames.shape[4]
    
            next_frames = []
            h_t = []
            c_t = []
    
            for i in range(self.num_layers):
                zeros = torch.zeros([batch, self.num_hidden[i], height, width]).to(device)
                h_t.append(zeros)
                c_t.append(zeros)
    
            for t in range(self.configs.pre_seq_length + self.configs.aft_seq_length - 1):
                # reverse schedule sampling
                if self.configs.reverse_scheduled_sampling == 1:
                    if t == 0:
                        net = frames[:, t]
                    else:
                        net = mask_true[:, t - 1] * frames[:, t] + (1 - mask_true[:, t - 1]) * x_gen
                else:
                    if t < self.configs.pre_seq_length:
                        net = frames[:, t]
                    else:
                        net = mask_true[:, t - self.configs.pre_seq_length] * frames[:, t] + \
                              (1 - mask_true[:, t - self.configs.pre_seq_length]) * x_gen
    
                h_t[0], c_t[0] = self.cell_list[0](net, h_t[0], c_t[0])
    
                for i in range(1, self.num_layers):
                    h_t[i], c_t[i] = self.cell_list[i](h_t[i - 1], h_t[i], c_t[i])
    
                x_gen = self.conv_last(h_t[self.num_layers - 1])
                next_frames.append(x_gen)
    
            # [length, batch, channel, height, width] -> [batch, length, height, width, channel]
            next_frames = torch.stack(next_frames, dim=0).permute(1, 0, 3, 4, 2).contiguous()
            if kwargs.get('return_loss', True):
                loss = self.MSE_criterion(next_frames, frames_tensor[:, 1:])
            else:
                loss = None
    
            return next_frames, loss
        
        
    
    
    
    
    
    
    # The input video frames are grayscale, thus single channel
    num_layers = 3
    num_hidden = [64, 64, 64]
    model = ConvLSTM_Model(num_layers, num_hidden, configs)
    # Loss function and optimizer
    criterion = torch.nn.MSELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
    
    for epoch in range(20):
        for sequences in dataloader_train:
            output = model(sequences)
    
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

`

TypeError: ConvLSTM_Model.forward() missing 1 required positional argument: 'mask_true'

**Comment by IsmailBData** [comment]
Heeeeeeeeeeeeeeeeelp

**Comment by chengtan9907** [comment]
Please refer to [openstl/methods/predrnn.py#Line 60](https://github.com/chengtan9907/OpenSTL/blob/OpenSTL-Lightning/openstl/methods/predrnn.py#L60).
