### ISSUE TITLE
export onnx

### ISSUE THREAD

**Issue by simonqian999** [chengtan9907/OpenSTL#106]
Thank you very much for your work, OpenSTL has been a great help to me. I've been attempting to export the model from OpenSTL to ONNX. In version 0.3, we were successful, and we placed the code for converting to ONNX within the training section. However, I've encountered some trouble with the Lightning version. Could you please inform me where I should place the output to ONNX? Thank you very much. We are also very willing to work with you to improve OpenSTL, as it is a very practical feature.

**Comment by chengtan9907** [comment]
Thank you for your kind and valuable contribution. I'm not familiar with ONNX. Could you please tell me what troubles you encountered with the lightning version? 
In fact, most of the algorithms did not change in the Lightning version. We use Lightning for its user-friendly training/inference but the core implementation is still the same. You can also use the previous branch [OpenSTLv0.3.0](https://github.com/chengtan9907/OpenSTL/tree/OpenSTLv0.3.0) for ONNX.

**Comment by chengtan9907** [comment]
I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.
