### ISSUE TITLE
for more detailed tutorials

### ISSUE THREAD

**Issue by Laymanpython** [chengtan9907/OpenSTL#108]
Do you have any more detailed tutorials for your project?When I set config file's sched to be :

sched = 'multistep'
decay_epoch = [50,100,150,200,300,400,500,600,700,800,900,1000]
decay_rate = 0.1
warmup_lr = 1e-5
warmup_epoch = 5

it says:TypeError: object of type 'int' has no len()

**Comment by chengtan9907** [comment]
Could you provide detailed information about this error? Which lines of code reported this error?

**Comment by chengtan9907** [comment]
I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.
