### ISSUE TITLE
关于Kitti数据集序列数目问题

### ISSUE THREAD

**Issue by lf-demo** [chengtan9907/OpenSTL#111]
你好，我按照10->1的序列生成KittiCaltech的训练集和测试集发现数目和论文中不一致。请问下论文中的数据集序列数量是10->10生成的结果么？如果是这样的话预测是只取第一帧结果构成10->1吗？还是说训练时是10->10呢？

**Comment by chengtan9907** [comment]
我们最近整理过数据集，应该按照实际代码实际跑出来的结果为准。训练和预测都是只取10->1的结果。

**Comment by chengtan9907** [comment]
I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.
