### ISSUE TITLE
where can I find implement of TAU  

### ISSUE THREAD

**Issue by treesirop** [chengtan9907/OpenSTL#115]
I did't find TAU.py on this file.

**Comment by chengtan9907** [comment]
TAU shares a similar model architecture with SimVP. Please refer to this file: [openstl/models/simvp_model.py](https://github.com/chengtan9907/OpenSTL/blob/OpenSTL-Lightning/openstl/models/simvp_model.py#L195).

**Comment by treesirop** [comment]
I got it ,thank you for your answer!



---Original---
From: "Cheng ***@***.***&gt;
Date: Mon, Mar 11, 2024 14:38 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [chengtan9907/OpenSTL] where can I find implement of TAU   (Issue#115)




 
TAU shares a similar model architecture with SimVP. Please refer to this file: openstl/models/simvp_model.py.

**Comment by chengtan9907** [comment]
I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.
