### ISSUE TITLE
kitti dataset problem

### ISSUE THREAD

**Issue by okayq** [chengtan9907/OpenSTL#118]
Have you encountered issues with parsing .hkl files downloaded from the KITTI dataset? Could it be related to the version of the hickle library?

**Comment by easewkx** [comment]
> 您是否在解析从 KITTI 数据集下载的 .hkl 文件时遇到问题？它可能与 hickle 库的版本有关吗？
May I ask if you have resolved it? I am also facing the same problem

**Comment by okayq** [comment]
> > 您是否在解析从 KITTI 数据集下载的 .hkl 文件时遇到问题？它可能与 hickle 库的版本有关吗？
> > May I ask if you have resolved it? I am also facing the same problem

Not yet.I'm still looking for a solution.

**Comment by chengtan9907** [comment]
Could you try to use the dataset from this source: https://figshare.com/articles/dataset/KITTI_hkl_files/7985684?

**Comment by chengtan9907** [comment]
I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.
