### ISSUE TITLE
请问为什么读取配置文件失败呢？

### ISSUE THREAD

**Issue by TongShi-Geodesy** [chengtan9907/OpenSTL#119]
loading config from configs/mmnist/simvp/SimVP_gSTA.py ...
warning: fail to load the config!

是不是设置的路径有问题？我是在windows系统的pycharm里面配置好环境运行的

**Comment by oduinihao** [comment]
看起来路径没有问题，我在ubuntu中能够正常运行

**Comment by chengtan9907** [comment]
I will close this issue because this issue has been solved by adding permission in Windows. Please feel free to open a new issue when you have new questions.
