### ISSUE TITLE
Kitti dataset FPS

### ISSUE THREAD

**Issue by YingtianDt** [chengtan9907/OpenSTL#120]
May I ask with what fps you trained models on Kitti dataset? Thanks.

**Comment by chengtan9907** [comment]
It was reported in our OpenSTL paper (Table 4).

**Comment by chengtan9907** [comment]
I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.

**Comment by YingtianDt** [comment]
Hi, I believe the data in Table 4 refers to the **processing FPS**, not the **video sampling FPS**. Could you also clarify the latter? Thanks!
