### ISSUE TITLE
Missing PredNet

### ISSUE THREAD

**Issue by YingtianDt** [chengtan9907/OpenSTL#121]
Hi, PredNet is mentioned in the document and model weight links, but the codes don't seem to implement it. Could you also provide the implementation?

**Comment by chengtan9907** [comment]
We removed it in the lightning version. But it can be found in the [OpenSTL 0.3.0](https://github.com/chengtan9907/OpenSTL/blob/OpenSTLv0.3.0/openstl/methods/prednet.py) branch.

**Comment by chengtan9907** [comment]
I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.
