### ISSUE TITLE
WaST

### ISSUE THREAD

**Issue by Ayt777** [chengtan9907/OpenSTL#122]
您好，请问WaST (AAAI'2024)已经发表了吗，标题是什么呢？

**Comment by Lupin1998** [comment]
Hi, @Ayt777. Thanks for interesting in WaST (Wavelet-Driven Spatiotemporal Predictive Learning: Bridging Frequency and Time Variations) and it is online at [AAAI'2024 webset](https://ojs.aaai.org/index.php/AAAI/article/view/28230).

**Comment by Ayt777** [comment]
谢谢！
