### ISSUE TITLE
How can OpenSTL be utilized in a time series prediction task?

### ISSUE THREAD

**Issue by whq1342** [chengtan9907/OpenSTL#123]
I am doing a multi-variate time series preiction task, but the form of the data in OpenSTL is like a two-dimension picture, so I am curioused about how can I use it for such task?
Waiting for your reponse!
Thanks a lot!

**Comment by chengtan9907** [comment]
I'm not familiar with such problems. You may need models like [Informer](https://github.com/zhouhaoyi/Informer2020).

**Comment by whq1342** [comment]
> I'm not familiar with such problems. You may need models like [Informer](https://github.com/zhouhaoyi/Informer2020).

thank you very much! Best wishes!
