### ISSUE TITLE
testing bug:ValueError: win_size exceeds image extent

### ISSUE THREAD

**Issue by sherlock-0327** [chengtan9907/OpenSTL#126]
The training parameters are as follows：
`python tools/train.py --dataname taxibj --method SimVP --config_file taxibj_simvp_gsta --ex_name taxibj_simvp_test --device cuda:0`
No error was reported during the model training process. After training, the testing reported the following error：
`ValueError: win_size exceeds image extent. Either ensure that your images are at least 7x7; or pass win_size explicitly in the function call, with an odd value less than or equal to the smaller side of your images. If your images are multichannel (with color channels), set channel_axis to the axis number corresponding to the channels.`
The version I used was `OpenSTL-Lightning`,and testing can\` t output anything but reporting the Testing DataLoader  had ready.
By the way, When I use `OpenSTL-3.0`，errors will be reported during training `ImportError: cannot import name 'setup_multi_processes' from 'openstl.utils'`,I checked and found that 'setup multi processes' introduced in tools/train.py is undefined in 'openstl==1.0.0', as are several other versions.

**Comment by kaka0910** [comment]
you can try to make the version of scikit-image less than 0.19

**Comment by sherlock-0327** [comment]
你好，邮件已收到，我会尽快查看（本条为自动回复）。hello,the email have been received,I will check it as soon as possible.

**Comment by chengtan9907** [comment]
I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.

**Comment by sherlock-0327** [comment]
你好，邮件已收到，我会尽快查看（本条为自动回复）。hello,the email have been received,I will check it as soon as possible.
