### ISSUE TITLE
problem for custom data

### ISSUE THREAD

**Issue by xgrfffff** [chengtan9907/OpenSTL#127]
Hi, thanks for your great work.I'm trying to run this code on sky img data, following the tutorial.ipynb , I run the project, but find that the prediction is strange. 
this is the log during the training process
![image](https://github.com/chengtan9907/OpenSTL/assets/77260462/2b099c41-a54f-42f4-9939-25de0908960a)
but for test, the mse is large
![image](https://github.com/chengtan9907/OpenSTL/assets/77260462/3788695c-cdd0-49ce-9497-9492437e2bc0)
and for visualization, the prediction is also stange.
![image](https://github.com/chengtan9907/OpenSTL/assets/77260462/83091c52-378a-4931-a545-9cb69202e87e)
I purely use your tutorial,with RGB data set values into [0,1] and use configs below, but the model doesn't seems to learn.
training with input 6 frames output 3 frames on about 30000 samples
![image](https://github.com/chengtan9907/OpenSTL/assets/77260462/b9f14d33-baa7-4054-81a2-2c81b0c27bc7)

your kindly relpy are highly appreciated

**Comment by StephenHung** [comment]
@xgrfffff So how the problem was solved?

**Comment by xgrfffff** [comment]
> @xgrfffff So how the problem was solved?

Nope, to be specific, this problem occurs when I test the temporarily saved model during training(which log low mse during training process). But when I use the best model after all training process, the problem disappear.
