### ISSUE TITLE
There is no tau model, where it is?

### ISSUE THREAD

**Issue by liukaiyueyuo** [chengtan9907/OpenSTL#128]
There is no tau model, where it is?

**Comment by chengtan9907** [comment]
TAU shares a similar model architecture with SimVP. Please refer to this file: [openstl/models/simvp_model.py](https://github.com/chengtan9907/OpenSTL/blob/OpenSTL-Lightning/openstl/models/simvp_model.py#L195).

**Comment by chengtan9907** [comment]
I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.
