### ISSUE TITLE
PredNet config file missing

### ISSUE THREAD

**Issue by YingtianDt** [chengtan9907/OpenSTL#132]
Hi, it seems the config file of PredNet is missing under `openstl/configs/kitticaltech/`. Could you please add it? Thanks!

**Comment by chengtan9907** [comment]
We found the implementation of this model may have some issues, so currently, we removed this model.

**Comment by chengtan9907** [comment]
I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.
