### ISSUE TITLE
Loading from checkpoint?

### ISSUE THREAD

**Issue by jamesafranke** [chengtan9907/OpenSTL#141]
Hi - Thanks so much for the amazing package. 

Is there any easy way to load a checkpoint so that I can do inference with the trained model. Something like:

```
.
.
exp = BaseExperiment(args, dataloaders=(dataloader_train, dataloader_val, dataloader_test), strategy='ddp')
PATH = './checkpoints/best.ckpt'
exp.load_from_checkpoint(PATH)

exp.eval()
y_hat = exp(x)
```

Thanks in advance!

**Comment by chengtan9907** [comment]
If you're using the PyTorch Lightning, you can refer to this document: [Saving and loading checkpoints](https://lightning.ai/docs/pytorch/stable/common/checkpointing_basic.html#lightningmodule-from-checkpoint)

**Comment by chengtan9907** [comment]
I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.
