### ISSUE TITLE
How to improve the performance

### ISSUE THREAD

**Issue by Crestina2001** [chengtan9907/OpenSTL#143]
![image](https://github.com/chengtan9907/OpenSTL/assets/87475993/a181ac30-087b-4bd0-a3c3-2918b10809df)
I tested TAU on MMNist with the following config(the model part is copied from this repo):
hid_S:16
hid_T:256
N_S:4
N_T:4
mlp_ratio:8
drop:0
drop_path:0
spatio_kernel_enc:3
spatio_kernel_dec:3
act_inplace:true
T:10
width:64
height:64
channel:1
lr:0.001
warmup_lr:0.00001
warmup_epoch:0
epochs:200
alpha:0.1
patience:5
batch_size:16
weight_decay:0

**Comment by Crestina2001** [comment]
I trained the TAU model for 500 epochs with default hyper params, and I got:
MSE: 31.08970
MAE: 87.31856
SSIM: 0.9147
PSNR: 21.5608

It has not converged, and here is the difference visualization:
![Figure_1](https://github.com/chengtan9907/OpenSTL/assets/87475993/02b57d6d-5564-4f27-aa6e-671f5474a38f)

**Comment by easewkx** [comment]
> I trained the TAU model for 500 epochs with default hyper params, and I got: MSE: 31.08970 MAE: 87.31856 SSIM: 0.9147 PSNR: 21.5608
> 
> It has not converged, and here is the difference visualization: ![Figure_1](https://private-user-images.githubusercontent.com/87475993/340897185-02b57d6d-5564-4f27-aa6e-671f5474a38f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTAxOTksIm5iZiI6MTcxOTk4OTg5OSwicGF0aCI6Ii84NzQ3NTk5My8zNDA4OTcxODUtMDJiNTdkNmQtNTU2NC00ZjI3LWFhNmUtNjcxZjU0NzRhMzhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA2NTgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMjhjZGY4MTYzZTc4OTIyMmRhZGJiZDllNzE2ZjZiMWMyYWRjYWY5OWVjYTIzMWRhN2ExMWNhYmI1NGY5N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nKTzE0ssX7Kq1ZNPdwDHhOnaETNnCaw3ur9GadTbHNY)

Do you have code for visualizing differences in the taxibj dataset? Can you provide it to me? Thank you.

**Comment by Crestina2001** [comment]
> > I trained the TAU model for 500 epochs with default hyper params, and I got: MSE: 31.08970 MAE: 87.31856 SSIM: 0.9147 PSNR: 21.5608
> > It has not converged, and here is the difference visualization: ![Figure_1](https://private-user-images.githubusercontent.com/87475993/340897185-02b57d6d-5564-4f27-aa6e-671f5474a38f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTAxOTksIm5iZiI6MTcxOTk4OTg5OSwicGF0aCI6Ii84NzQ3NTk5My8zNDA4OTcxODUtMDJiNTdkNmQtNTU2NC00ZjI3LWFhNmUtNjcxZjU0NzRhMzhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA2NTgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMjhjZGY4MTYzZTc4OTIyMmRhZGJiZDllNzE2ZjZiMWMyYWRjYWY5OWVjYTIzMWRhN2ExMWNhYmI1NGY5N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nKTzE0ssX7Kq1ZNPdwDHhOnaETNnCaw3ur9GadTbHNY)
> 
> Do you have code for visualizing differences in the taxibj dataset? Can you provide it to me? Thank you.

Oh, I deleted that part. Just subtract the ground truth from the predictions or vice versa. Ask AI to write it for you.

**Comment by easewkx** [comment]
> > > 我使用默认超参数训练了 500 个 epoch 的 TAU 模型，我得到了： MSE：31.08970 MAE：87.31856 SSIM：0.9147 PSNR：21.5608 它没有收敛，这是差异可视化：![Figure_1](https://private-user-images.githubusercontent.com/87475993/340897185-02b57d6d-5564-4f27-aa6e-671f5474a38f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTAxOTksIm5iZiI6MTcxOTk4OTg5OSwicGF0aCI6Ii84NzQ3NTk5My8zNDA4OTcxODUtMDJiNTdkNmQtNTU2NC00ZjI3LWFhNmUtNjcxZjU0NzRhMzhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA2NTgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMjhjZGY4MTYzZTc4OTIyMmRhZGJiZDllNzE2ZjZiMWMyYWRjYWY5OWVjYTIzMWRhN2ExMWNhYmI1NGY5N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nKTzE0ssX7Kq1ZNPdwDHhOnaETNnCaw3ur9GadTbHNY)
> > 
> > 
> > 您是否有用于可视化 taxibj 数据集中差异的代码？你能给我吗？谢谢。
> 
> 哦，我删除了那部分。只需从预测中减去基本事实，反之亦然。让 AI 为你写。

Thank you, I have already resolved it.

**Comment by chengtan9907** [comment]
> ![image](https://private-user-images.githubusercontent.com/87475993/340544748-a181ac30-087b-4bd0-a3c3-2918b10809df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMTMwODksIm5iZiI6MTcyMjIxMjc4OSwicGF0aCI6Ii84NzQ3NTk5My8zNDA1NDQ3NDgtYTE4MWFjMzAtMDg3Yi00YmQwLWEzYzMtMjkxOGIxMDgwOWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDAwMjYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmMWEyOWYzZjBiMmQ0NjQwNmQzOTNhOTg2NzlhNzQwODEzMDFhYTliNGM5N2JlMmUzNWVmYjM4NWE0N2RlZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KF01ZFlhXlsgB3wjXmkw1hE2URZU78sQI6MQV-mWa6M) I tested TAU on MMNist with the following config(the model part is copied from this repo): hid_S:16 hid_T:256 N_S:4 N_T:4 mlp_ratio:8 drop:0 drop_path:0 spatio_kernel_enc:3 spatio_kernel_dec:3 act_inplace:true T:10 width:64 height:64 channel:1 lr:0.001 warmup_lr:0.00001 warmup_epoch:0 epochs:200 alpha:0.1 patience:5 batch_size:16 weight_decay:0

Could you please provide the full log file? I'm not sure about the reason of this issue.

**Comment by Crestina2001** [comment]
> > ![image](https://private-user-images.githubusercontent.com/87475993/340544748-a181ac30-087b-4bd0-a3c3-2918b10809df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMTMwODksIm5iZiI6MTcyMjIxMjc4OSwicGF0aCI6Ii84NzQ3NTk5My8zNDA1NDQ3NDgtYTE4MWFjMzAtMDg3Yi00YmQwLWEzYzMtMjkxOGIxMDgwOWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDAwMjYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmMWEyOWYzZjBiMmQ0NjQwNmQzOTNhOTg2NzlhNzQwODEzMDFhYTliNGM5N2JlMmUzNWVmYjM4NWE0N2RlZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KF01ZFlhXlsgB3wjXmkw1hE2URZU78sQI6MQV-mWa6M) I tested TAU on MMNist with the following config(the model part is copied from this repo): hid_S:16 hid_T:256 N_S:4 N_T:4 mlp_ratio:8 drop:0 drop_path:0 spatio_kernel_enc:3 spatio_kernel_dec:3 act_inplace:true T:10 width:64 height:64 channel:1 lr:0.001 warmup_lr:0.00001 warmup_epoch:0 epochs:200 alpha:0.1 patience:5 batch_size:16 weight_decay:0
> 
> Could you please provide the full log file? I'm not sure about the reason of this issue.

I have partially solved this problem. I have obtained a MSE of about 25. Here are the parameters I used:
{
    "hid_S": 64,
    "hid_T": 512,
    "N_S": 4,
    "N_T": 8,
    "mlp_ratio": 8.0,
    "drop": 0.0,
    "drop_path": 0.0,
    "spatio_kernel_enc": 3,
    "spatio_kernel_dec": 3,
    "act_inplace": true,
    "T": 10,
    "width": 64,
    "height": 64,
    "channel": 1,
    "num_objects": [
        2
    ],
    "lr": 0.001,
    "warmup_lr": 1e-05,
    "warmup_epoch": 0,
    "epochs": 200,
    "alpha": 0.1,
    "patience": 5,
    "batch_size": 16,
    "weight_decay": 0
}

Could you give suggestions about how to improve the performance. The solution can be either scaling up this model(TAU), or using any other models. My GPU has a RAM of 40 GB, so too large a model may not fit in. 

I have also tried simvp, and I got a MSE of 33 on MMnist, with the following config:
{
    "alpha": 0.1,
    "hid_S": 64,
    "hid_T": 512,
    "N_S": 4,
    "N_T": 8,
    "mlp_ratio": 8.0,
    "drop": 0.0,
    "drop_path": 0.0,
    "spatio_kernel_enc": 3,
    "spatio_kernel_dec": 3,
    "width": 64,
    "height": 64,
    "channel": 1,
    "num_objects": [
        2
    ],
    "scaling_factor": 1.0,
    "n_frames_input": 10,
    "n_frames_output": 10,
    "lr": 0.001,
    "warmup_lr": 1e-05,
    "warmup_epoch": 0,
    "epochs": 200,
    "patience": 5,
    "micro_batch_size": 16,
    "macro_batch_size": 16,
    "weight_decay": 0,
    "min_lr": 1e-05,
    "dataset_name": "mmnist",
    "algorithm_name": "simvp"
}
But when I transferred it to a custom dataset(precipitation nowcasting dataset), the algorithm failed to converge(even after tuning the lr). TAU can work on the custom dataset, but I want to improve the performance though. 
Could you give any insights on how to scale up simvp, and make it work on complex datasets? 

Many thanks!

**Comment by chengtan9907** [comment]
You may need to try some generative techniques, like adding diffusion models after the deterministic prediction from TAU.

**Comment by chengtan9907** [comment]
I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.
