### ISSUE TITLE
关于weatherbench预测的mv预测时间的问题

### ISSUE THREAD

**Issue by gaoxiaomo** [chengtan9907/OpenSTL#144]
我们给出的mv_4结果是预测的28时间步长还是4个时间步长，即采用的是mv_4_28还是mv_4_4

**Comment by chengtan9907** [comment]
如果是从4帧预测4帧就用mv_4_4，如果是从4帧预测28帧就用mv_4_28。

**Comment by chengtan9907** [comment]
I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.
