### ISSUE TITLE
early stopping 

### ISSUE THREAD

**Issue by IsmailBData** [chengtan9907/OpenSTL#146]
Hi,

how can i specify early stopping?

Thanks

**Comment by chengtan9907** [comment]
PyTorch lightning itself supports early stopping. You may add a callback in [api/exp.py](https://github.com/chengtan9907/OpenSTL/blob/a54b36be208bed70e216dc4cc38b0c5109f42a6a/openstl/api/exp.py#L50). The early stopping callback can be referred in [lightning docs](https://lightning.ai/docs/pytorch/stable/common/early_stopping.html#early-stopping).

**Comment by chengtan9907** [comment]
I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.
