### ISSUE TITLE
Issue about visualizations

### ISSUE THREAD

**Issue by gaojiawei321** [chengtan9907/OpenSTL#148]
I meet the following questions when visualization:

QObject::moveToThread: Current thread (0x563ef1b873e0) is not the object's thread (0x563ef1e90380).
Cannot move to target thread (0x563ef1b873e0)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/inspur/anaconda3/envs/OpenSTL/lib/python3.10/site-packages/opencv_python-4.10.0.84-py3.10-linux-x86_64.egg/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, minimal, minimalegl, offscreen, vnc, webgl.

I found some discussion on Google, but none can fix it. Does anyone know how to fix this problem?

Thanks so much

**Comment by chengtan9907** [comment]
It seems to be an environmental problem, not a problem from OpenSSL. I would suggest you look for some other discussions.
