### ISSUE TITLE
TypeError: SwinTransformerBlock.__init__() got an unexpected keyword argument 'proj_drop'

### ISSUE THREAD

**Issue by 15650326960** [chengtan9907/OpenSTL#154]
Dear author, this problem occurred when I was training the SimVP_Swim model. I tried to change several timm versions, but it was not solved. Do you have a solution?
![屏幕截图 2024-09-11 104416](https://github.com/user-attachments/assets/0be15b8b-c814-431f-a740-fa81255010a0)

**Comment by chengtan9907** [comment]
It seems to be the problem of the updated timm because our repo does not include the definition of SwinTransformerBlock.

**Comment by Nanming666** [comment]
你好解决了吗，我也遇到了同样的问题

**Comment by Nanming666** [comment]
我的timm版本是0.6.11，但是也会有这个问题
