### ISSUE TITLE
Error when using trained ConvLSTM with new dataset

### ISSUE THREAD

**Issue by BlackRab** [chengtan9907/OpenSTL#157]
Hello. I'm a newer to OpenSTL. I've trained a ConvLSTM, the shape of the input is (n, 12, 1, 64, 64), where n is the number of samples, and the shape of output is (n, 24, 1, 64, 64). But when I use the trained model to predict on a new dataset, I've met an error:
`TypeError: forward() missing 1 required positional argument: 'batch_y'`

The code for prediction is as follows:
```
predj = trainer.predict(model, dipti)
```
where dipti is a dataloader with data shape of (1, 12, 1 64, 64).

How can I solve this error? Thanks!

**Comment by chengtan9907** [comment]
`trainer.predict` is the API from PyTorch Lightning. I think you should use the forward of `ConvLSTM_Model` in inference.

**Comment by BlackRab** [comment]
Thank you for your reply! Yes, it works when I use the forward method.

**Comment by chengtan9907** [comment]
I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.
