### ISSUE TITLE
How to use pretrained models on model zoo?

### ISSUE THREAD

**Issue by gunesevitan** [chengtan9907/OpenSTL#158]
Is there any easy straightforward way to finetune model weights listed [here](https://github.com/chengtan9907/OpenSTL/blob/OpenSTL-Lightning/docs/en/model_zoos/video_benchmarks.md)? I tried to set value of `ckpt_path` in my config files, but it didn't work because none of them had `pytorch_lightning_version` in their model files. I think all of them are state_dicts. In this case what should be the workaround because trainer uses `openstl.methods.ModelClass.load_from_checkpoint` which always checks the `pytorch_lightning_version` key in model files.

**Comment by chengtan9907** [comment]
Lightning's checkpoint has many keys, including state_dict. We only need state_dict when for the model itself. For example, model.load(torch.load('path_to_state_dict')).

**Comment by chengtan9907** [comment]
I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.
