### ISSUE TITLE
Significant Improvement in Reproduced Results in OpenSTL Compared to Original Papers

### ISSUE THREAD

**Issue by May2001** [chengtan9907/OpenSTL#159]
Hello, I noticed that in OpenSTL, the reproduced results for many methods are significantly better than those in their original papers. For example, the MSE value of ConvLSTM on the MMNIST dataset is 103.3 in the original paper, while in OpenSTL it is only 29.8. What is the reason for such a significant improvement?

**Comment by gunesevitan** [comment]
I noticed that too. ConvLSTM paper is from 2015 and at that time modern techniques that we use today like AdamW and cyclic learning rates weren't around. It's probably similar to how Ross Wightman trained ResNets using lots of new stuff and got improvements [here](https://arxiv.org/abs/2110.00476).

**Comment by chengtan9907** [comment]
Yes. I was also surprised by the results of ConvLSTM when I run it under our OpenSTL. It seems this baseline was underestimated.

**Comment by chengtan9907** [comment]
I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.
