### ISSUE TITLE
Slow training speedmnist dataset in google Colab

### ISSUE THREAD

**Issue by nathantambeur** [chengtan9907/OpenSTL#16]
Hi all,

First of all thank you for the amazing work and codebase. I was experimenting with training the model on the mnist dataset in google Colab  but had training times of 1h+ per epoch. This is strange considering the "V1" SIMVP only took about 2min per epoch. Did anyone have a similar issue? Could the problem be that google Colab only provides +/- 10 gb of ram?

Thanks in advanced!

**Comment by chengtan9907** [comment]
Hi there, sorry for the late reply. Have I solved this issue yet?

**Comment by chengtan9907** [comment]
I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.
