### ISSUE TITLE
Predictions using OpenSTL

### ISSUE THREAD

**Issue by cadam00** [chengtan9907/OpenSTL#167]
Hi,

How to make predictions using OpenSTL?

For example, in your [tutorial for custom data](https://github.com/chengtan9907/OpenSTL/tree/OpenSTL-Lightning/examples/tutorial.ipynb) at `examples/tutorial` you train a model and you assign it on the variable named `exp` at subsection 3.2, `In [13]`. So, how to use this `exp` to make predictions like the `./work_dirs/custom_exp/saved/trues.npy` you provide? In other words, how to use something like `exp.predict(X_new)` to get the corresponding predictions for a new unknown dataset `X_new`?

Thanks.

**Comment by BlackRab** [comment]
Hi, this is the way I use for predictions, I hope it will help you. If you have trained a SimVP model, you can use it on a new dataset as follows:

```
from openstl.methods import SimVP
model = SimVP.load_from_checkpoint(ckptdir) # ckptdir is the file path saved the model
y = model(X_new)
```

**Comment by cadam00** [comment]
So, I should not use the code for `BaseExperiment` from `openstl.api`, but rather importing the needed method directly from `openstl.methods`?

**Comment by BlackRab** [comment]
This way works for me. There may be another way to use the model with `BaseExperiment`.

You can refer to this issue: [](https://github.com/chengtan9907/OpenSTL/issues/141)

**Comment by BlackRab** [comment]
This way works for me. There may be another way to use the model with BaseExperiment.

You can refer to this issue: https://github.com/chengtan9907/OpenSTL/issues/141

**Comment by cadam00** [comment]
Ok ok I got it!!! Thanks a lot!!!

Moreover, I found out that something like
`y = exp.method(torch.tensor(X_new))`
will work as well!

**Comment by chengtan9907** [comment]
@BlackRab Many thanks for your reply!
