### ISSUE TITLE
Pre training model

### ISSUE THREAD

**Issue by MSrobt** [chengtan9907/OpenSTL#18]
Thank you for sharing

I am very interested in your work. If possible, could you share the pre trained models on the SimVP taxibj dataset with me.

**Comment by Lupin1998** [comment]
Hi @MSrobt. Thanks for using `OpenSTL` and raising the question. Currently, we are working on refactoring and adding new features to `OpenSTL`, and we will upload trained models and logs for video prediction benchmarks as soon as possible (maybe in two weeks).
