### ISSUE TITLE
Caltech Dataset Download

### ISSUE THREAD

**Issue by MSrobt** [chengtan9907/OpenSTL#21]
Thank you for sharing

I encountered some issues while using the Caltech dataset. The dataset downloaded from your network disk contains many empty files with a size of 0b. If possible, could you please test it_ data_ Could you please upload the gzip.hkl and fileidx.hkl files again.

**Comment by Lupin1998** [comment]
Hi, @MSrobt. Sorry for the many data in the uploaded Caltech dataset. We have lost some data due to the migration of GPU servers. We will update the full dataset soon, or you can download the Caltech dataset according to experiment setups in [prednet](https://github.com/coxlab/prednet/).
