### ISSUE TITLE
Example 'mmnist' run not working

### ISSUE THREAD

**Issue by ajikmr** [chengtan9907/OpenSTL#26]
Hello.

I just installed OpenSTL and tried to run 'mmnist' example case given in your documentation. 
-----
/*******/OpenSTL/data has following files

> ls data/moving_mnist/
mnist_cifar_test_seq.npy  mnist_cifar_test_seq.npy.tar  mnist_test_seq.npy  train-images-idx3-ubyte.gz
--------
Error message when I run mmnist case using command given in your documentation. 'dataloader.py' does not seem to have handle for mmnist.

  File "/******/OpenSTL/tools/train.py", line 40, in <module>
    exp = BaseExperiment(args)
  File "/******/OpenSTL/openstl/api/train.py", line 48, in __init__
    self._preparation()
  File "/******/OpenSTL/openstl/api/train.py", line 129, in _preparation
    self._get_data()
  File "/******/OpenSTL/openstl/api/train.py", line 199, in _get_data
    get_dataset(self.args.dataname, self.config)
  File "/******/OpenSTL/openstl/utils/main_utils.py", line 151, in get_dataset
    return load_data(**config)
  File "/******/OpenSTL/openstl/datasets/dataloader.py", line 43, in load_data
    raise ValueError(f'Dataname {dataname} is unsupported')
ValueError: Dataname mmnist is unsupported

**Comment by chengtan9907** [comment]
Thank you for your interest in our work and the questions you raised. A few days ago, while updating the code, we accidentally deleted the dataloader for Moving MNIST. We have now fixed this issue, and you can try git pull the newest code. 

Please refer to the commit: https://github.com/chengtan9907/OpenSTL/commit/3434e0a12c243dfc768fb3956d421327f3940ec3

**Comment by ajikmr** [comment]
Thanks you very much for your prompt response.
