### ISSUE TITLE
prepare KTH dataset 

### ISSUE THREAD

**Issue by zzzzzx-1115** [chengtan9907/OpenSTL#27]
Hello, I am trying to train SimVP in KTH, but I find the [tool for KTH](https://github.com/chengtan9907/OpenSTL/blob/master/tools/prepare_data/download_kth.sh) seems not enough. 

After unzipping those .zip files, I got a lot of .avi videos. However, according to the [dataloader script](https://github.com/chengtan9907/OpenSTL/blob/master/openstl/datasets/dataloader_kth.py#L185), I think under directories like 'boxing', there should be some images of shape (1000, 1000), but I only got .avi consisting of frames of shape (120, 160). 

Could you please tell me if there are any steps I forget to take to perform training in KTH dataset? Thank you!

**Comment by Lupin1998** [comment]
Hi, @zzzzzx-1115, thanks for using OpenSTL. As for the KTH dataset, all frames under the `.avi` folder should be $120\times 160$ resolutions, and we can reproduce the preparation with [download_kth.sh](https://github.com/chengtan9907/OpenSTL/blob/master/tools/prepare_data/download_kth.sh). We resize the frame to $128\times 128$ for the KTH experiments. Therefore, you can perform training on the KTH dataset after executing [download_kth.sh](https://github.com/chengtan9907/OpenSTL/blob/master/tools/prepare_data/download_kth.sh).

**Comment by Lupin1998** [comment]
Hello, we have fixed the preparation of the KTH dataset and also uploaded `kth_action.zip` to Baidu Cloud. Please download the image version of the KTH action, and feel free to raise questions if more issues occur.

**Comment by zzzzzx-1115** [comment]
Thanks for your response! I will try later.
