### ISSUE TITLE
Conda create error for nni pkg.

### ISSUE THREAD

**Issue by surpace0924** [chengtan9907/OpenSTL#33]
Hi! I appreciate your wonderful project.
I have a question about the nni package installation error.

I encountered a "ResolvePackageNotFound:nni" error when I tried to "conda create" in my environment.

I checked the previous pullrequests in this repository for this problem.
And I noticed that the fix was done in #15 .

However, I noticed that the change was reverted in the commit b678838 .

Was this change intended?
Thank you in advance.

**Comment by Lupin1998** [comment]
Hello, @surpace0924. Thanks for pointing out the bug in installing nni package. I have fixed this issue as you recommend in the latest commit. Thanks again for your help, and I will close this issue if there is no more problem.

**Comment by surpace0924** [comment]
Thank you for your quick fix!
