### ISSUE TITLE
About TaxiBJ Dataset

### ISSUE THREAD

**Issue by GFZShiwai** [chengtan9907/OpenSTL#34]
May I ask how you divided the training and test sets for this dataset? In order to compare the results with those in modelzoo, I would like to divide the data in the same way as you used. Can you provide the `taxibj/dataset.npz` file?

**Comment by Lupin1998** [comment]
Hi, @GFZShiwai, thanks for using OpenSTL. As mentioned in [Installation](https://github.com/chengtan9907/OpenSTL/tree/master/docs/en/install.md), we provide the version we used in experiments from [**Baidu Cloud**](https://pan.baidu.com/s/1fudsBHyrf3nbt-7d42YWWg?pwd=kjfk) (kjfk), and you can find `taxibj/dataset.npz`. I will close this issue if there is no more questions.
