### ISSUE TITLE
可视化模型过程中的问题

### ISSUE THREAD

**Issue by tjnkyqcy** [chengtan9907/OpenSTL#35]
您好，非常感谢您再STL模型方面做出的贡献，给我提供了很多帮助。
我想请教一下，从问题“kth数据集问题 https://github.com/chengtan9907/OpenSTL/issues/28”@JCChen778中发现了和我遇到类似的问题，但是我依然没有解决，希望得到您的指导。
我的问题：在进行可视化的时候遇到提示错误：
E:\Anaconda3\envs\pytorch-gpu-openSTL\python.exe H:/OpenSTL-master/tools/visualizations/vis_video.py -d mmnist -w work_dirs/Debug --index 0 --save_dirs fig_mmnist_vis
Traceback (most recent call last):
File "H:/OpenSTL-master/tools/visualizations/vis_video.py", line 136, in
main()
File "H:/OpenSTL-master/tools/visualizations/vis_video.py", line 45, in main
assert os.path.isdir(args.work_dirs)
AssertionError

Process finished with exit code 1
开始怀疑可能是work_dir的路径不正确，按照可视化文档（docs/en/visualization/video_visualization.md）中的指令进行修改后，
-d mmnist -w work_dirs/Debug --index 0 --save_dirs fig_mmnist_vis
仍然不能解决，以下是我从官网下载程序包并训练之后得到的文件的相关结构，是否与您的相同。谢谢。

OpenSTL-master
|--tools
| |--visualizations
| | |--vis_video.py
| |--work_dirs
| | |--Debug
| | | |--checkpoints
| | | | |--lastest.pth

**Comment by huajiao-330** [comment]
你好，建议试试-d mmnist -w ../work_dirs/Debug --index 0 --save_dirs yoursavedirs --vis_channel -1

**Comment by chengtan9907** [comment]
I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.
