### ISSUE TITLE
How to add early stop during training?

### ISSUE THREAD

**Issue by Pachark** [chengtan9907/OpenSTL#36]
Nice work! Is early training an available option for OpenSTL?

**Comment by Pachark** [comment]
btw, is it possible to apply multiple gpus when training?

**Comment by Lupin1998** [comment]
Hi, @Pachark. Thanks for your questions and suggestions. We have added `--early_stop_epoch` for the early-stop training in the latest commit. As for distributed training, you can use `tools/dist_tran.sh` to start training and refer to [get_started.md](https://github.com/chengtan9907/OpenSTL/tree/master/docs/en/get_started.md) for details. I will close this issue, and you can open a new one for further questions.
