### ISSUE TITLE
About the updated download_taxibj.sh file and his dataset

### ISSUE THREAD

**Issue by tjnkyqcy** [chengtan9907/OpenSTL#39]
First of all, thank you very much for your work.
I saw your update about the taxibj dataset and showed the format of the dataset in tools\prepare_data\download_taxibj.sh. I downloaded https://github.com/chengtan9907/OpenSTL/releases/download/v0.1.0/taxibj_dataset.zip
dataset and looked at the format of the .npz file.

My problem is that by looking at the X_train dataset in .npz, he structure is (20461,4,2,32,32) for a 5D tensor data. But in the original author's explanation of the dataset you gave it shows that the dataset is a 4D tensor, so I would like to ask you what does this 5D structure represent respectively?

**Comment by tjnkyqcy** [comment]
Also, when I train,test and visualize the taxibj dataset in vis_vidio.py, the result shows not the traffic data corresponding to taxibj but the visualized heatmap of the mmnist dataset, the taxibj dataset you provided has a different structure than the original author's dataset, are you sure this is correct?

**Comment by chengtan9907** [comment]
The first dimension is the number of data samples. (20461,4,2,32,32) is corresponding to (B, T, C, H, W).
