### ISSUE TITLE
Error while executing the training code

### ISSUE THREAD

**Issue by heweibing222** [chengtan9907/OpenSTL#40]
Hello！
Thanks for your excellent program. I have installed the program following the steps given, but when I am ready to execute the training example you have given, I get the following error:

```
(OpenSTL) heweibing@ubuntusrv:~/DeepLearning/OpenSTL$ python tools/train.py -d mmnist --lr 1e-3 -c configs/mmnist/simvp/SimVP_gSTA.py --ex_name mmnist_simvp_gsta
Traceback (most recent call last):
  File "/home/disk15t/heweibing/DeepLearning/OpenSTL/tools/train.py", line 7, in <module>
    from openstl.api import BaseExperiment
  File "/home/disk15t/heweibing/DeepLearning/OpenSTL/openstl/api/__init__.py", line 3, in <module>
    from .train import BaseExperiment
  File "/home/disk15t/heweibing/DeepLearning/OpenSTL/openstl/api/train.py", line 15, in <module>
    from openstl.core import Hook, metric, Recorder, get_priority, hook_maps
  File "/home/disk15t/heweibing/DeepLearning/OpenSTL/openstl/core/__init__.py", line 7, in <module>
    from .optim_scheduler import get_optim_scheduler
  File "/home/disk15t/heweibing/DeepLearning/OpenSTL/openstl/core/optim_scheduler.py", line 4, in <module>
    from timm.optim.adafactor import Adafactor
  File "/usr/local/anaconda3/envs/OpenSTL/lib/python3.11/site-packages/timm/__init__.py", line 2, in <module>
    from .models import create_model, list_models, is_model, list_modules, model_entrypoint, \
  File "/usr/local/anaconda3/envs/OpenSTL/lib/python3.11/site-packages/timm/models/__init__.py", line 28, in <module>
    from .maxxvit import *
  File "/usr/local/anaconda3/envs/OpenSTL/lib/python3.11/site-packages/timm/models/maxxvit.py", line 216, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/local/anaconda3/envs/OpenSTL/lib/python3.11/dataclasses.py", line 1221, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/local/anaconda3/envs/OpenSTL/lib/python3.11/dataclasses.py", line 1211, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/OpenSTL/lib/python3.11/dataclasses.py", line 959, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/OpenSTL/lib/python3.11/dataclasses.py", line 816, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'timm.models.maxxvit.MaxxVitConvCfg'> for field conv_cfg is not allowed: use default_factory
```

Do you know if there was an error? How do I fix it?

I would greatly appreciate it if you could provide me with some assistance.

**Comment by chengtan9907** [comment]
This may appear to be a timm version issue, please check if the timm version matches.

**Comment by m-muaz** [comment]
I am having a similar error. I have checked the installed timm version in my conda environment and it obeys the requirement provided in environment.yml file. @heweibing222 Did you by any chance fixed this issue?

**Comment by Lupin1998** [comment]
Hello, please try to install a certain version of timm (0.5.4, 0.6.2, 0.6.7, or 0.6.11). At least, I haven't met the mentioned error with these timm versions with various PyTorch versions (1.10, 1.12, 1.13). Hope this will be helpful to you.

**Comment by m-muaz** [comment]
I created the OpenSTL conda environment using the environment and the following is the output of `conda list` that shows the version of packages. Here, the installed version of timm package is 0.6.11 whereas pytorch has version 2.0.1 . Could that be the reason for the aforementioned issue.


# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
astor                     0.8.1                    pypi_0    pypi
blas                      2.116                       mkl    conda-forge
blas-devel                3.9.0            16_linux64_mkl    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.19.1               hd590300_0    conda-forge
ca-certificates           2023.7.22            hbcca054_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2023.7.22                pypi_0    pypi
cftime                    1.6.2                    pypi_0    pypi
charset-normalizer        3.2.0                    pypi_0    pypi
click                     8.1.6                    pypi_0    pypi
cloudpickle               2.2.1                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
contextlib2               21.6.0                   pypi_0    pypi
contourpy                 1.1.0                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
dask                      2023.8.0                 pypi_0    pypi
decord                    0.6.0                    pypi_0    pypi
dill                      0.3.7                    pypi_0    pypi
filelock                  3.11.0                   pypi_0    pypi
fonttools                 4.42.0                   pypi_0    pypi
fsspec                    2023.6.0                 pypi_0    pypi
future                    0.18.3                   pypi_0    pypi
fvcore                    0.1.5.post20221221          pypi_0    pypi
gmp                       6.2.1                h58526e2_0    conda-forge
gmpy2                     2.1.2           py311h6a5fa03_1    conda-forge
h5py                      3.9.0           nompi_py311he78b9b8_101    conda-forge
hdf5                      1.14.1          nompi_h4f84152_100    conda-forge
hickle                    3.4.5                      py_0    conda-forge
huggingface-hub           0.16.4                   pypi_0    pypi
icu                       72.1                 hcb278e6_0    conda-forge
idna                      3.4                      pypi_0    pypi
imageio                   2.31.1                   pypi_0    pypi
importlib-metadata        6.8.0                    pypi_0    pypi
iopath                    0.1.10                   pypi_0    pypi
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.3.1                    pypi_0    pypi
json-tricks               3.17.2                   pypi_0    pypi
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4                    pypi_0    pypi
krb5                      1.21.1               h659d440_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libaec                    1.0.6                hcb278e6_1    conda-forge
libblas                   3.9.0            16_linux64_mkl    conda-forge
libcblas                  3.9.0            16_linux64_mkl    conda-forge
libcurl                   8.2.1                hca28451_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.1.0               he5830b7_0    conda-forge
libgfortran-ng            13.1.0               h69a702a_0    conda-forge
libgfortran5              13.1.0               h15d22d2_0    conda-forge
libhwloc                  2.9.2           nocuda_h7313eea_1008    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
liblapack                 3.9.0            16_linux64_mkl    conda-forge
liblapacke                3.9.0            16_linux64_mkl    conda-forge
libnghttp2                1.52.0               h61bc06f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsqlite                 3.42.0               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.1.0               hfd8a6a1_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxml2                   2.11.4               h0d562d8_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
llvm-openmp               16.0.6               h4dfa4b3_0    conda-forge
locket                    1.0.0                    pypi_0    pypi
lpips                     0.1.4                    pypi_0    pypi
markupsafe                2.1.3           py311h459d7ec_0    conda-forge
matplotlib                3.7.2                    pypi_0    pypi
mkl                       2022.1.0           h84fe81f_915    conda-forge
mkl-devel                 2022.1.0           ha770c72_916    conda-forge
mkl-include               2022.1.0           h84fe81f_915    conda-forge
mpc                       1.3.1                hfe3b2da_0    conda-forge
mpfr                      4.2.0                hb012696_0    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  hcb278e6_0    conda-forge
netcdf4                   1.6.4                    pypi_0    pypi
networkx                  3.1                pyhd8ed1ab_0    conda-forge
nni                       2.10.1                   pypi_0    pypi
numpy                     1.25.2          py311h64a7726_0    conda-forge
opencv-python             4.8.0.74                 pypi_0    pypi
openssl                   3.1.2                hd590300_0    conda-forge
openstl                   0.3.0                     dev_0    <develop>
packaging                 23.1                     pypi_0    pypi
pandas                    2.0.3                    pypi_0    pypi
partd                     1.4.0                    pypi_0    pypi
pillow                    10.0.0                   pypi_0    pypi
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
portalocker               2.7.0                    pypi_0    pypi
prettytable               3.8.0                    pypi_0    pypi
psutil                    5.9.5                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.11.4          hab00c5b_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.11                    3_cp311    conda-forge
pythonwebhdfs             0.2.3                    pypi_0    pypi
pytorch                   2.0.1              py3.11_cpu_0    pytorch
pytorch-mutex             1.0                         cpu    pytorch
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h8228510_1    conda-forge
requests                  2.31.0                   pypi_0    pypi
responses                 0.23.3                   pypi_0    pypi
rocm-smi                  5.6.0                h59595ed_1    conda-forge
schema                    0.7.5                    pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scikit-learn              1.3.0                    pypi_0    pypi
scipy                     1.11.1                   pypi_0    pypi
setuptools                68.0.0             pyhd8ed1ab_0    conda-forge
simplejson                3.19.1                   pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
sympy                     1.12            pypyh9d50eac_103    conda-forge
tabulate                  0.9.0                    pypi_0    pypi
tbb                       2021.10.0            h00ab1b0_0    conda-forge
termcolor                 2.3.0                    pypi_0    pypi
threadpoolctl             3.2.0                    pypi_0    pypi
tifffile                  2023.7.18                pypi_0    pypi
timm                      0.6.11                   pypi_0    pypi
tk                        8.6.12               h27826a3_0    conda-forge
toolz                     0.12.0                   pypi_0    pypi
torchvision               0.15.2                   pypi_0    pypi
tqdm                      4.65.1                   pypi_0    pypi
typeguard                 2.13.3                   pypi_0    pypi
types-pyyaml              6.0.12.11                pypi_0    pypi
typing_extensions         4.7.1              pyha770c72_0    conda-forge
tzdata                    2023.3                   pypi_0    pypi
urllib3                   2.0.4                    pypi_0    pypi
wcwidth                   0.2.6                    pypi_0    pypi
websockets                11.0.3                   pypi_0    pypi
wheel                     0.41.1             pyhd8ed1ab_0    conda-forge
xarray                    0.19.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yacs                      0.1.8                    pypi_0    pypi
zipp                      3.16.2                   pypi_0    pypi
zstd                      1.5.2                hfc55251_7    conda-forge

**Comment by m-muaz** [comment]
I installed 0.6.7 version of timm package and it worked for me. Thanks for the help!

**Comment by chengtan9907** [comment]
I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.
