### ISSUE TITLE
Categorical data

### ISSUE THREAD

**Issue by mauriciodev** [chengtan9907/OpenSTL#44]
Hello, researchers.
Thank you for sharing the valuable code with us. I understand that most modules could be used on categorical data by adding a softmax to the end of the models and using categorical metrics (accuracy, f-score, etc). 
Is this in your plans for the library?

**Comment by chengtan9907** [comment]
Thank you for your interest! At present, our research primarily concentrates on spatial-temporal predictive learning. Your suggestion is excellent, and we will certainly consider and discuss the potential of incorporating it.

**Comment by chengtan9907** [comment]
I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.
