### ISSUE TITLE
Question about time step is different between input and output.

### ISSUE THREAD

**Issue by AprilDomLin** [chengtan9907/OpenSTL#45]
Really thank you for your excellent contribution of STL.
However, I cannot forecast using SimVP mdoel while time step of  input and output are different. So, I'd like to ask for the solving.

e.g.
input of the model is like B * T1 * C1 * H * W.
I'd like to got a output whose shape is B * T2 * C2 * H * W, which T2 is longer than T1.

**Comment by chengtan9907** [comment]
Hi,

We have provided `pre_seq_length` and `aft_seq_length` in the SimVP model to accommodate video frames of varying lengths. These parameters can be adjusted to suit the requirements of your specific project.

**Comment by AprilDomLin** [comment]
> Hi,
> 
> We have provided `pre_seq_length` and `aft_seq_length` in the SimVP model to accommodate video frames of varying lengths. These parameters can be adjusted to suit the requirements of your specific project.

Really thank you for your reply.
I have a idea of  how you implemented this. However, is that ignored different temporal information, only using dupicated prediction?

In fact, I have tried to modify the code on openstl in this days. Do you think that is the other idea to solve this problem, I add the Conv2d 1*1 to transform time dim of `skip`  into T2.

**Comment by chengtan9907** [comment]
We tried this strategy and found that the two strategies usually get similar performance. The current strategy have less parameters, so we chose it.

**Comment by AprilDomLin** [comment]
> We tried this strategy and found that the two strategies usually get similar performance. The current strategy have less parameters, so we chose it.

I got it. Really thank you again!

**Comment by chengtan9907** [comment]
I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.
