### ISSUE TITLE
How to create own projects using OpenSTL and train on multiple GPUs

### ISSUE THREAD

**Issue by tarun360** [chengtan9907/OpenSTL#49]
Hello,

I was following `tutorial.ipynb` in `examples/` directory. This example does single GPU training. I wanted to extend this to multi-GPU (single node) training. How can I do do this?

I have tried the following approach till now but I am not sure it's correct:

I tried adding to `custom_training_config` the following parameters:
```
    'use_gpu': True,
    'dist': True,
    'launcher': 'pytorch',
```

After this I would need to specify envvars such as `RANK`, `WORLD_SIZE`, `MASTER_ADDR`, `MASTER_PORT`. What value should I specify for `RANK`? Shouldn't it be auto set while spawning multiple processes?

**Comment by hzy0211** [comment]
Please check this instruction: https://github.com/chengtan9907/OpenSTL/blob/master/docs/en/get_started.md#training-and-testing-with-multiple-gpus
