### ISSUE TITLE
SSIM and PSNR seem weird for t2m_5625

### ISSUE THREAD

**Issue by zzzzzx-1115** [chengtan9907/OpenSTL#54]
I conducted experiments on some datasets provided by you, and I got SSIM and PSNR as expected except for the t2m_5625 dataset:

- the SSIM is a small positive close to 0 (4.673859322470631e-07 for different models and different checkpoints)
- the PSRN is a negative (-48.89913024845931 for different models and different checkpoints)

I think that's the reason why the paper (journal version of SimVP) does not contain SSIM or PSNR for this dataset. Could you please tell me why this happens? Thank you!

**Comment by chengtan9907** [comment]
I think it is because the scale of general images is fixed between [0,1], while the scale of weatherbench data is different.

**Comment by zzzzzx-1115** [comment]
> I think it is because the scale of general images is fixed between [0,1], while the scale of weatherbench data is different.

Thank you. I will check again later.
