### ISSUE TITLE
How can I use the tool to make predictions?

### ISSUE THREAD

**Issue by CXL-edu** [chengtan9907/OpenSTL#55]
Can I use the tool to make predictions? I only see interfaces for training, validation and testing.

When I play a competition, I don't have labeled data from the test set, can I use the trained model to predict the outcome?

**Comment by chengtan9907** [comment]
It seems that you can refer to the tutorial ([examples/tutorial.ipynb](https://github.com/chengtan9907/OpenSTL/blob/master/examples/tutorial.ipynb)).

**Comment by chengtan9907** [comment]
If you have a video, you can split it into two segments, one for a given frame and one for the frame you need to predict.

I don't quite understand your latter question. We save `pred.npy` when testing and then load the prediction when visualizing. Why did you say that's not the actual prediction results?

**Comment by CXL-edu** [comment]
您提到的第一句话是基于我已知全部信息的情况。您说的将视频分割成两部分帧，后一部分作为需要预测的值，实际上我是没有这部分信息的。我看到models的源代码中是有`_predict`方法的，但是由于库的集成度比较高，我没法直接使用。

假设我有历史的2帧信息`x`，需要预测未来2帧信息`y`，但是我没有未来数据`y`。比赛通常会给出`train_set`，`test_sample`，在`train_set`上我可以任意的分割出`x`和`y`，但是`test_sample`仅提供`x`。更具体的说假设数据格式是`(batch, time_step, channel, h, w)`，那么`train_set`将会是`(b, 4, c, h, w)`，而`test_sample`将会是`(b, 2, c, h, w)`。

**Comment by CXL-edu** [comment]
关于`pred.npy`，我想说的是我不知道这个预测结果是怎么得到的，而我使用这个库就是希望能得到好的prediction，因此我需要通过`tutorial`学习到如何使用`OpenSTL`进行预测。

**Comment by chengtan9907** [comment]
It sounds a bit strange. I'm sorry that I have no idea about your competition.

**Comment by chengtan9907** [comment]
I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.
