### ISSUE TITLE
TAU的模型源码在哪呢

### ISSUE THREAD

**Issue by HaiXiang-Zhao** [chengtan9907/OpenSTL#56]
我看openstl里只有老模型啊
![image](https://github.com/chengtan9907/OpenSTL/assets/67145546/108ecbbb-2ea7-4433-b54a-67d81ed530d3)

**Comment by chengtan9907** [comment]
TAU的模型在：https://github.com/chengtan9907/OpenSTL/blob/master/openstl/models/simvp_model.py#L196，模型架构跟SimVP类似，中间的Temporal module是TAU。

**Comment by chengtan9907** [comment]
I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.
