### ISSUE TITLE
Inconsistent reproduction results on Moving MNIST

### ISSUE THREAD

**Issue by LintureGrant** [chengtan9907/OpenSTL#57]
hi, thk u for your code and your excellent work!

I have encountered some problems when i  reproduce the SimVP-sSTA*10 in your paper, which should has a performance of 15.0 on MSE. 

**Actually,** before i reproduce the SimVP-sSTA*10, the SimVP-sSTA, which means train 200 epoch, was shown the consistent 26.6 mse performance reported in your paper. **So i can believe the code that i download and the configuration is right.** 

**However,** when i train the right SimVP-sSTA for 2K epoch, which means the SimVP-sSTA*10 model, it has a bad performance of 24.5 on MSE. I tried to figure out the inconsistent reproduction, but there is no more detail in your paper about how to train the SimVP-sSTA for 2000 epoch.

Hopefully you could answer this question and provide more training details about the SimVP-sSTA*10 so that i can reproduce your result. 

Thanks!

**Comment by chengtan9907** [comment]
I think it should not be that bad. Could you please provide your train log file?

**Comment by Lupin1998** [comment]
Hi, @LintureGrant, thanks for using OpenSTL, and you can refer to our trained models and logs of SimVP+gSTA on Moving MNIST, [model](https://github.com/chengtan9907/OpenSTL/releases/download/mmnist-weights/mmnist_simvp_s_gsta_one_ep2000.pth) and [log](https://github.com/chengtan9907/OpenSTL/releases/download/mmnist-weights/mmnist_simvp_s_gsta_one_ep2000.log). The 200-epoch and 2000-epoch experiments share similar hyper-parameters.

**Comment by LintureGrant** [comment]
> I think it should not be that bad. Could you please provide your train log file?

sure, there is the log file under the 200 epoch and the 2000 epoch training condition
[train_20230905_171434.log](https://github.com/chengtan9907/OpenSTL/files/12573133/train_20230905_171434.log)
[train_20230907_102117.log](https://github.com/chengtan9907/OpenSTL/files/12573161/train_20230907_102117.log)

**Comment by LintureGrant** [comment]
> Hi, @LintureGrant, thanks for using OpenSTL, and you can refer to our trained models and logs of SimVP+gSTA on Moving MNIST, [model](https://github.com/chengtan9907/OpenSTL/releases/download/mmnist-weights/mmnist_simvp_s_gsta_one_ep2000.pth) and [log](https://github.com/chengtan9907/OpenSTL/releases/download/mmnist-weights/mmnist_simvp_s_gsta_one_ep2000.log). The 200-epoch and 2000-epoch experiments share similar hyper-parameters.

Thank u for your rely. I noticed that the code that prints this log file doesn't seem to match the code in the current GitHub repository. 

Then I plotted the convergence curve based on the log file you provided and the results are below. Such a convergence curve doesn't seem very natural, compared to the convergence curve of simvp+incepU.
![397268704e8b4d2c74407bfbb84ac46](https://github.com/chengtan9907/OpenSTL/assets/81279002/2b81b106-8617-4a2f-81a5-0d84364a2a69)

**Comment by Lupin1998** [comment]
Thanks for your comment. Please notice that the provided model and log of SimVP+gSTA for 2000-epoch training were reproduced by the old version of OpenSTL, [SimVPv2](https://github.com/chengtan9907/OpenSTL/tree/SimVPv2). If you think the convergence curve is unnatural, you can plot other recurrent-free methods of 2000-epoch training on MMNIST, e.g., SimVP+VAN, SimVP+MogaNet, and TAU.

**Comment by chengtan9907** [comment]
I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.
