### ISSUE TITLE
Running error: No module named 'openstl'

### ISSUE THREAD

**Issue by hxhebit** [chengtan9907/OpenSTL#58]
When I run `python tools/train.py -d mmnist --lr 1e-3 -c configs/mmnist/simvp/SimVP_gSTA.py --ex_name mmnist_simvp_gsta`, it raises the error:

```
Traceback (most recent call last):
  File "/home/hehanxiang/OpenSTL/tools/train.py", line 8, in <module>
    from openstl.api.train import BaseExperiment
ModuleNotFoundError: No module named 'openstl'
```

**Comment by Lupin1998** [comment]
Hi, @hxhebit. Have you tried to install OpenSTL following [install.md](https://github.com/chengtan9907/OpenSTL/blob/master/docs/en/install.md), where `python setup.py develop` will setup `openstl`?

**Comment by chengtan9907** [comment]
I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.
