### ISSUE TITLE
Problem on Running Test

### ISSUE THREAD

**Issue by netlabcode** [chengtan9907/OpenSTL#60]
I got this problem when I ran the test. mse = exp.test() , Is there any potential solution for this problems?

```
OpenSTL\openstl\api\train.py", line 359, in test
    metrics=metric_list, channel_names=channel_names, spatial_norm=spatial_norm)

OpenSTL\openstl\core\metrics.py", line 188, in metric
    true[b, f].swapaxes(0, 2), multichannel=True)
**TypeError: 'NoneType' object is not callable**
```

**Comment by Lupin1998** [comment]
Hi, @netlabcode, thanks for your question. Could you please provide detailed information for this problem, e.g., the config file and full outputs of errors?

**Comment by chengtan9907** [comment]
I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.
