### ISSUE TITLE
ValueError: mutable default <class 'timm.models.maxxvit.MaxxVitConvCfg'> for field conv_cfg is not allowed: use default_factory

### ISSUE THREAD

**Issue by yyyujintang** [chengtan9907/OpenSTL#62]
I follow the previous steps

> git clone https://github.com/chengtan9907/OpenSTL
cd OpenSTL
conda env create -f environment.yml
conda activate OpenSTL
python setup.py develop
bash tools/prepare_data/download_mmnist.sh
python tools/train.py -d mmnist --lr 1e-3 -c configs/mmnist/simvp/SimVP_gSTA.py --ex_name mmnist_simvp_gsta

And the bug comes up

> ValueError: mutable default <class 'timm.models.maxxvit.MaxxVitConvCfg'> for field conv_cfg is not allowed: use default_factory

I tried to fix it and I found [this](https://github.com/huggingface/pytorch-image-models/issues/1530) in StackOverflow.

It seems it's a bug caused by Python version 3.11. And I checked your environment.yml and install.md, you suggest Python 3.7+ .
But following the  environment.yml, the latest Python version will be installed and the bug will arise.

I suggest you change python to python==3.x((eg, 3.9, which I check is OK) in environment.yml.

In case others meet this bug. Thank you!

**Comment by weiyanle** [comment]
Thanks a lot, I encountered the same issue too! Since there are so many dependence, it seems like I can't simply downgrade the python, but only reinstall the environment, which wastes a lot of time😢

**Comment by Lupin1998** [comment]
Hi, I have tried to install environments with Python>=3.11.x and the same error occurred. But Python==3.10.x can work. Maybe a better choice is to create a new conda env and reinstall the environments by `python setup.py develop`.
```shell
conda create -n openstl python=3.10
pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu116
conda activate openstl
python setup.py develop
```

**Comment by SPOOKEXE** [comment]
If you want to stay on the later (unsupported) versions still, here is a fix for the issue:
https://github.com/huggingface/pytorch-image-models/issues/1530#issuecomment-1411722938

Also include 'field' in the "from dataclass import ..." statement at the top of the python file located at 'kohya_ss-22.1.0\venv\Lib\site-packages\timm\models\maxxvit.py'

**Comment by Coin1026** [comment]
> Hi, I have tried to install environments with Python>=3.11.x and the same error occurred. But Python==3.10.x can work. Maybe a better choice is to create a new conda env and reinstall the environments by `python setup.py develop`.
> 
> ```shell
> conda create -n openstl python=3.10
> pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu116
> conda activate openstl
> python setup.py develop
> ```

I have made this mistake according to your steps. May I ask how to solve it？
error: Pillow 10.1.0 is installed but pillow<10.1.0,>=8.3.2 is required by {'imageio'}

**Comment by Coin1026** [comment]
I change the python version to 3.9 and 3.10, but the bug occured, and if i change pillow to 8.3.2 ,another bug occured.
error: Pillow 10.1.0 is installed but pillow<10.1.0,>=8.3.2 is required by {'imageio'}
error: Pillow 8.3.2 is installed but pillow!=8.3.*,>=5.3.0 is required by {'torchvision'}

**Comment by chengtan9907** [comment]
I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.
