### ISSUE TITLE
It does not run after creating the environment

### ISSUE THREAD

**Issue by gqqarno** [chengtan9907/OpenSTL#63]
Follow the command to install the environment test , torch.cuda.is_availiable() is false.

**Comment by yyyujintang** [comment]
Make sure you have installed a version of PyTorch that is compatible with your CUDA version. You can find the compatible PyTorch version on the official PyTorch website. Install PyTorch with CUDA support using the appropriate pip command. For example:
`pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by gqqarno** [comment]
thank you. I have update the environment.yml.   

name: OpenSTL
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - numpy
  - hickle
  - pip
  - python=3.9
  - pytorch=1.12.0
  - cudatoolkit=11.3
  - torchvision=0.13.0
  - xarray==0.19.0
  - pip:
    - decord
    - fvcore
    - lpips
    - nni
    - pandas
    - scikit-image<=0.19.3
    - timm<=0.6.11
    - tqdm
prefix: /opt/anaconda3/envs/openstl


add the version information and cudatookit information

**Comment by gqqarno** [comment]
感谢

1400372595
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chengtan9907/OpenSTL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月11日(星期三) 上午10:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chengtan9907/OpenSTL] It does not run after creating the environment (Issue #63)





 
Make sure you have installed a version of PyTorch that is compatible with your CUDA version. You can find the compatible PyTorch version on the official PyTorch website. Install PyTorch with CUDA support using the appropriate pip command. For example:
 pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by Lupin1998** [comment]
Hi, thanks for the question and updating `environment.yml`. We will update the environment in the latest commit. I will close this issue if there is no more question.
