### ISSUE TITLE
A clerical error at examples/tutorial.ipynb

### ISSUE THREAD

**Issue by weiyanle** [chengtan9907/OpenSTL#64]
> 1.2 Load the dataset and visualize an example
> in [4]: `# C, H, W: the height, width, channel of each frame`

Here should be the channel, height, width of each frame
I know my issue may seem dumb but it's better to be serious. Thank you for your excellent work!

**Comment by chengtan9907** [comment]
Thanks for your kind reminder! We have fixed this in the recent commit [0a0f36c](https://github.com/chengtan9907/OpenSTL/commit/0a0f36c0eb917a199d0310a209bc5fd751d1c5e6).
