### ISSUE TITLE
Out-of-memory problem when reproducing KittiCaltech and Human3.6M dataset

### ISSUE THREAD

**Issue by Pachark** [chengtan9907/OpenSTL#66]
Hi, I've encountered OOM issues when training SimVP-gSTA model for KittiCaltech and Human3.6M dataset.

My GPU device is a single V100. What's the GPU device of official implementation for these two datasets? 

Maybe I need a single A100 for SimVP-gSTA to avoid OOM?

**Comment by YangLiYL1994** [comment]
have you tried smaller batch size?

**Comment by YangLiYL1994** [comment]
> > have you tried smaller batch size?
> 
> Yes. But smaller batch size cannot guarantee SOTA results.

That's the only solution for your out-of-memory issue. You can either choose to train the model in a smaller batch size or FP16 mixed precision. I don't understand why you think a smaller batch size would affect performance. From my experience, the batch size doesn't really affect performance a lot.

**Comment by Lupin1998** [comment]
> Hi, I've encountered OOM issues when training SimVP-gSTA model for KittiCaltech and Human3.6M dataset.
> 
> My GPU device is a single V100. What's the GPU device of official implementation for these two datasets?
> 
> Maybe I need a single A100 for SimVP-gSTA to avoid OOM?

Hi, @Pachark, thanks for your question. We suggest you use 4xGPUs to reproduce Human3.6M experiments, which require A100-40G or V100-32G. You might need 8xGPUs with small memory.
