### ISSUE TITLE
Prediction with flexible length

### ISSUE THREAD

**Issue by bszzhzxyf** [chengtan9907/OpenSTL#67]
one thing I want to do is training with flexible length using custom data, but nothing about it in the github, so can you explain how to run the code and it is in which folder.
thanks for your reply.

**Comment by Lupin1998** [comment]
Hi, @bszzhzxyf. Thanks for using OpenSTL and sorry for the late reply. As for flexible length prediction tasks, it hasn't been supported by the current version of OpenSTL. You may to the padding of the input and the output to generate the prediction and then remove the padding frames to get the final results.

**Comment by chengtan9907** [comment]
Please take a look at the file [openstl/datasets/dataset_constant.py](https://github.com/chengtan9907/OpenSTL/blob/master/openstl/datasets/dataset_constant.py) for reference. It is important to define the lengths of the input and output frames, specified by `pre_seq_length` and `aft_seq_length`, respectively. The total_length is calculated as the sum of pre_seq_length and aft_seq_length.

**Comment by chengtan9907** [comment]
I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.
