### ISSUE TITLE
google colab tutorial not working

### ISSUE THREAD

**Issue by TheMarcosP** [chengtan9907/OpenSTL#69]
after running all cells, when setting up the enviroment i get:
`
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-14-1efd4377d66c>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from openstl.api import BaseExperiment
      2 from openstl.utils import create_parser
      3 
      4 args = create_parser().parse_args([])
      5 config = args.__dict__

1 frames
[/content/OpenSTL/openstl/api/train.py](https://localhost:8080/#) in <module>
      8 import numpy as np
      9 from typing import Dict, List
---> 10 from fvcore.nn import FlopCountAnalysis, flop_count_table
     11 
     12 import torch

ModuleNotFoundError: No module named 'fvcore'
`

i tried installing fvcore myself with pip and by cloning from facebook reasearch repo but it just does not work

**Comment by chengtan9907** [comment]
I've come across a similar issue. Could you please take a look at [issue #32](https://github.com/chengtan9907/OpenSTL/issues/32) to see if the solution is applicable to your case?

**Comment by nabeelraza-7** [comment]
You need to restart the kernel after installing. It worked for me.

**Comment by chengtan9907** [comment]
I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.
