### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by ISMAILWORLD** [chengtan9907/OpenSTL#70]
exp = BaseExperiment(args, dataloaders=(dataloader_train, dataloader_val, dataloader_test)) this ligne raised me an error, i do not know how could i fix it ? Any help !

**Comment by chengtan9907** [comment]
It seems that `method` or `model_type` is not specified. Are these two variables `None`?

**Comment by ISMAILWORLD** [comment]
> It seems that `method` or `model_type` is not specified. Are these two variables `None`?



    sched_lower = args.sched.lower()         #########################THIS LINE############################
    total_steps = epoch * steps_per_epoch
    by_epoch = True
    if sched_lower == 'onecycle':
        lr_scheduler = optim.lr_scheduler.OneCycleLR(
            optimizer,
            max_lr=args.lr,
            total_steps=total_steps,
            final_div_factor=getattr(args, 'final_div_factor', 1e4))
        by_epoch = False
    elif sched_lower == 'cosine':
        lr_scheduler = CosineLRScheduler(
            optimizer,
            t_initial=epoch,
            lr_min=args.min_lr,
            warmup_lr_init=args.warmup_lr,
            warmup_t=args.warmup_epoch,
            t_in_epochs=True,  # update lr by_epoch
            k_decay=getattr(args, 'lr_k_decay', 1.0))
    elif sched_lower == 'tanh':
        lr_scheduler = TanhLRScheduler(
            optimizer,
            t_initial=epoch,
            lr_min=args.min_lr,
            warmup_lr_init=args.warmup_lr,
            warmup_t=args.warmup_epoch,
            t_in_epochs=True)  # update lr by_epoch
    elif sched_lower == 'step':
        lr_scheduler = StepLRScheduler(
            optimizer,
            decay_t=args.decay_epoch,
            decay_rate=args.decay_rate,
            warmup_lr_init=args.warmup_lr,
            warmup_t=args.warmup_epoch)
    elif sched_lower == 'multistep':
        lr_scheduler = MultiStepLRScheduler(
            optimizer,
            decay_t=args.decay_epoch,
            decay_rate=args.decay_rate,
            warmup_lr_init=args.warmup_lr,
            warmup_t=args.warmup_epoch)
    else:
        assert False and "Invalid scheduler"

    return optimizer, lr_scheduler, by_epoch

**Comment by ISMAILWORLD** [comment]
> It seems that `method` or `model_type` is not specified. Are these two variables `None`?

And please tell me what are thos variables     what they do exactely ??
    'N_S': 4,
    'N_T': 8,
    'hid_S': 64,
    'hid_T': 256

Those as well ?

    'pre_seq_length': pre_seq_length,
    'aft_seq_length': aft_seq_length,

and tell me 

# the shape is B x T x C x H x W
# B: the number of samples
# T: the number of frames in each sample
# C, H, W: the height, width, channel of each frame

the channel is the third variable or the last one.



Thank you so much

**Comment by chengtan9907** [comment]
You could specify the `sched `. For example, `--sched onecycle `. 

The channel is the third one, and we have fixed this comment in commit [#0a0f36c](https://github.com/chengtan9907/OpenSTL/commit/0a0f36c0eb917a199d0310a209bc5fd751d1c5e6).

**Comment by chengtan9907** [comment]
I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.

**Comment by ISMAILWORLD** [comment]
> You could specify the `sched `. For example, `--sched onecycle `.
> 
> The channel is the third one, and we have fixed this comment in commit [#0a0f36c](https://github.com/chengtan9907/OpenSTL/commit/0a0f36c0eb917a199d0310a209bc5fd751d1c5e6).

Ok cool it works
