### ISSUE TITLE
在jupyter notebook中运行example/tutorial.ipynb报错：ModuleNotFoundError: No module named 'openstl'

### ISSUE THREAD

**Issue by cabbage17** [chengtan9907/OpenSTL#71]
在jupyter notebook中运行example/tutorial报错：ModuleNotFoundError: No module named 'openstl'
但是相同的代码在pycharm中可以运行
在同一个环境下，已使用sys.path检查路径，pycharm和jupyter的路径完全一致

**Comment by chengtan9907** [comment]
You need to verify whether OpenSTL has been correctly installed (using python setup.py develop) in the environment to your Jupyter kernel.

**Comment by cabbage17** [comment]
> You need to verify whether OpenSTL has been correctly installed (using python setup.py develop) in the environment to your Jupyter kernel.

thanks,i have tried but it doesn't work

**Comment by chengtan9907** [comment]
You can run `!pip list | grep OpenSTL` command in the juypter block to see if OpenSTL is correctly installed. Could you show me the output of such a command?

**Comment by cabbage17** [comment]
> You can run `!pip list | grep OpenSTL` command in the juypter block to see if OpenSTL is correctly installed. Could you show me the output of such a command?

I re-run 'python setup.py develop', the error has been  solved! Thank you very much again!

**Comment by chengtan9907** [comment]
I‘m glad to see the issue is solved. 

I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.
