### ISSUE TITLE
'N_S': 4, 'N_T': 8, 'hid_S': 64, 'hid_T': 256

### ISSUE THREAD

**Issue by ISMAILWORLD** [chengtan9907/OpenSTL#72]
Hello!

 please what are thosz variables, what they do exactely, are they a hyperparameter or what ??

**Comment by chengtan9907** [comment]
Yes, these are the hyperparameters for the SimVP models. 'N_S' refers to the number of spatial blocks, 'N_T' denotes the number of temporal blocks, 'hid_S' is the hidden size of the spatial blocks, and 'hid_T' represents the hidden size of the temporal blocks.

If you find this repository helpful, please give it a star.

**Comment by ISMAILWORLD** [comment]
> Yes, these are the hyperparameters for the SimVP models. 'N_S' refers to the number of spatial blocks, 'N_T' denotes the number of temporal blocks, 'hid_S' is the hidden size of the spatial blocks, and 'hid_T' represents the hidden size of the temporal blocks.
> 
> If you find this repository helpful, please give it a star.

so for each model there are some hyperparameters to specify? , cuz i am intresed in using predrnn++ i do not know if there are hyperparameters that i should specify or left the ones of SimVP. otherwise is there any help file where i could find a little tutorial  for each model(its hyperparameters and ..)

Thank u in advance

**Comment by ISMAILWORLD** [comment]
> Yes, these are the hyperparameters for the SimVP models. 'N_S' refers to the number of spatial blocks, 'N_T' denotes the number of temporal blocks, 'hid_S' is the hidden size of the spatial blocks, and 'hid_T' represents the hidden size of the temporal blocks.
> 
> If you find this repository helpful, please give it a star.

it is so helpful of course i will

**Comment by chengtan9907** [comment]
> > Yes, these are the hyperparameters for the SimVP models. 'N_S' refers to the number of spatial blocks, 'N_T' denotes the number of temporal blocks, 'hid_S' is the hidden size of the spatial blocks, and 'hid_T' represents the hidden size of the temporal blocks.
> > If you find this repository helpful, please give it a star.
> 
> so for each model there are some hyperparameters to specify? , cuz i am intresed in using predrnn++ i do not know if there are hyperparameters that i should specify or left the ones of SimVP. otherwise is there any help file where i could find a little tutorial for each model(its hyperparameters and ..)
> 
> Thank u in advance

There are config files in `openstl/configs` for each dataset. The most important hyperparameters are in those files. For example, Moving MNIST - PredRNNpp [openstl/configs/mmnist/PredRNNpp.py](https://github.com/chengtan9907/OpenSTL/blob/master/configs/mmnist/PredRNNpp.py).

**Comment by chengtan9907** [comment]
I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.
