### ISSUE TITLE
How to use the simvp model in custom

### ISSUE THREAD

**Issue by HaiXiang-Zhao** [chengtan9907/OpenSTL#75]
How to use the simvp model in custom in the example, set method='method ':' SimVP ',' model '_ Type ': None, but found' model 'after running_ Type ':' gSTA 'is not like this becoming Simvp_ Is v2 ready? How should I set up to run simvp

**Comment by chengtan9907** [comment]
'model_type': 'gSTA' is SimVPv2. It is correct.

**Comment by chengtan9907** [comment]
I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.
