### ISSUE TITLE
load the checkpoint.pth

### ISSUE THREAD

**Issue by xualiencd** [chengtan9907/OpenSTL#80]
Hello, please tell me how to load the checkpoint.pth weights that have been trained when testing? Moreover, assuming that the training is to input 10 frames and output 20 frames, how to input 10 frames and output 30 frames during testing? The 10 frames of the test input are the same as the training input, and the first 20 frames of the test output are also the same as the training output. I want to get the last 10 frames of the 30 frames of the test output.
Looking forward to reply, thank you.

**Comment by mhy9989** [comment]
You can consider taking the last 10 frames of the output 20 frames as input to predict the next 30 frames and the last 40 frames. In fact, during training, predictions beyond the actual dimensions are made by changing the output into input.

**Comment by chengtan9907** [comment]
@mhy9989, Thank you for your kind answer.

I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.
