### ISSUE TITLE
关于'in_shape'维度的问题

### ISSUE THREAD

**Issue by tjnkyqcy** [chengtan9907/OpenSTL#81]
openstl/datasets/dataset_constant.py路径下的'in_shape': [10, 3, 128, 128]是一个4维张量，第一个维度是Batch Size么？如果第一个维度是Batch Size，那么在openstl/utils/parser.py路径下的参数：parser.add_argument('--batch_size', '-b', default=2, type=int, help='Training batch size')设置是否有必要一致，或者我理解的不对呢？

**Comment by xualiencd** [comment]
你好，请问一下如何指定用第几张显卡呢，我看默认使用cuda:0，看了好久都不会指定

**Comment by chengtan9907** [comment]
第一个维度是输入帧的数量，3是通道数，(128, 128)是宽、高。
