### ISSUE TITLE
Support for recent works

### ISSUE THREAD

**Issue by zzzzzx-1115** [chengtan9907/OpenSTL#82]
Are you going to include recently published methods (e.g., SwinLSTM and MMVP, which are both accepted by ICCV2023) in Model Zoo?

Thanks for your awesome OpenSTL again!

**Comment by chengtan9907** [comment]
Thank you for your suggestions. We have implemented these two methods in our new branch `OpenSTL-Lightning`. Thanks for the effort by @54wb.

**Comment by chengtan9907** [comment]
I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.
