### ISSUE TITLE
Questions about dataloader_kth.py

### ISSUE THREAD

**Issue by tjnkyqcy** [chengtan9907/OpenSTL#87]
dataloader_kth.py

class DataProcess(object):
    """Class for preprocessing dataset inputs."""

    def __init__(self, input_param):
        self.paths = input_param['paths']
        **self.category_1** = ['handwaving', 'walking']#, 
        **self.category_2** = ['running']#, 
        self.category = self.category_1 + self.category_2
        self.image_width = input_param['image_width']

        self.train_person = [
            '01','02','03','04', '05','06', '07', '08', '09', '10', '11', '12','13', '14', '15', '16'
        ]#
        self.test_person = ['17', '18', '19','20', '21', '22',]#'23', '24', '25' ,'26'()

        self.input_param = input_param
        self.seq_len = input_param['seq_length']

def load_data(self, path, mode='train'):

...
c_dir_list = self.category
        frame_category_flag = -1
        for c_dir in c_dir_list:  # handwaving
            if c_dir in **self.category_1**:
                frame_category_flag = 1  # 20 step
            elif c_dir in **self.category_2**:
                frame_category_flag = 2  # 3 step
            else:
                print('category error!!!')
...

Why are there two categories category_1 and category_2 for sequences? And what is the purpose of setting different step sizes for the two categories? Is there a categorization problem here? Please explain, thank you.

**Comment by chengtan9907** [comment]
We follow the previous works in this setting, see [predrnn-pytorch/core/data_provider/kth_action.py](https://github.com/thuml/predrnn-pytorch/blob/master/core/data_provider/kth_action.py#L109).

**Comment by tjnkyqcy** [comment]
def __init__(self, input_param):
        self.paths = input_param['paths']  # path to parent folder containing category dirs
        self.category_1 = ['boxing', 'handclapping', 'handwaving', 'walking']
        self.category_2 = ['jogging', 'running']
        self.categories = self.category_1 + self.category_2
        self.image_width = input_param['image_width']
...
 for cat_dir in self.categories: # handwaving
            if cat_dir in self.category_1:
                frame_category_flag = 1 # 20 step
            elif cat_dir in self.category_2:
                frame_category_flag = 2 # 3 step
            else:
                raise Exception("category error!!!")

From here it looks like you are dividing all sequences into 2 categories and setting a step size of 20 for category 1 sequences and 3 for category 2 sequences. I'm not sure if I'm understanding this correctly, but what I don't understand is why you are setting it up this way, is there something I'm not understanding? Why not set all sequences to the same step size?

**Comment by chengtan9907** [comment]
That's a good question... We just follow the same experimental setting of previous works. I'm not sure why they did this.

**Comment by chengtan9907** [comment]
I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.
