### ISSUE TITLE
Input image height (128) doesn't match model (256).

### ISSUE THREAD

**Issue by NoahRe1** [chengtan9907/OpenSTL#88]
After changing the patch_size of SwinLSTM_B to 4, an error occurred: `Input image height (128) doesn't match model (256).`

This error is coming from this piece of code:

```
class PatchInflated(nn.Module):
    def __init__(self, in_chans, embed_dim, input_resolution, stride=2, padding=1, output_padding=1):
        super(PatchInflated, self).__init__()

        stride = to_2tuple(stride)
        padding = to_2tuple(padding)
        output_padding = to_2tuple(output_padding)
        self.input_resolution = input_resolution

        self.Conv = nn.ConvTranspose2d(in_channels=embed_dim, out_channels=in_chans, kernel_size=(3, 3),
                                       stride=stride, padding=padding, output_padding=output_padding)
```

It performs upsampling with a factor of 2, and when the patch_size is 4, the output no longer matches the original image size.

**Comment by 54wb** [comment]
Hi,

Thank you very much for your interest! We have also noticed this bug and asked for the anthor about it, you can reference this https://github.com/SongTang-x/SwinLSTM/issues/5#issuecomment-1858239480 issue for add a new layer to upsample the input. We also will update this code for later. Hope my answer makes sense to you.

Best regards,

**Comment by chengtan9907** [comment]
I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.
