### ISSUE TITLE
cur_seq = batch_x.clone()

### ISSUE THREAD

**Issue by rs-lsl** [chengtan9907/OpenSTL#89]
Hello, thank you very much for the excellent open source network framework. I have a question to ask. In most models, when making iterative predictions in the training stage, there is a line of code called：`cur_seq = batch_x.clone()`，may I ask what the function/role of 'clone' is here? Is it necessory? Is it to prevent gradient vanishing/exploding problems? If we remove this clone and input the original variable directly, is it possible? I have tried to remove the 'clone' and the performance will decrease, but I have not figured out the specific reason. Thank you very much

**Comment by chengtan9907** [comment]
Well, it is my personal coding style. I found it is necessary sometimes so I always use it. I think it should not affect the performance much here...

Did the performance decrease a lot?

**Comment by chengtan9907** [comment]
I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.

**Comment by rs-lsl** [comment]
Thanks, the performance is not decrease a lot and seems has not influence.

**Comment by chengtan9907** [comment]
Thanks for your reply.
