### ISSUE TITLE
SimVP-IncepU-L and SimVP-gSTA-L Perform Worse Than Standard Version

### ISSUE THREAD

**Issue by YangLi309** [chengtan9907/OpenSTL#90]
Hi there,

I've been working with the SimVP models, including the enhanced 'L' versions which offer expanded dimension sizes and increased numbers of encoder and translator layers. These models have shown promising results on the MMNIST dataset, as illustrated in the attached screenshot:
![result1](https://github.com/chengtan9907/OpenSTL/assets/103625917/abfe17e8-05c5-4e18-8918-23a8db519bfd)

However, I've encountered some performance challenges when testing these models on the KITTICaltech and KTH datasets. Notably, the 'L' versions seem to underperform compared to the standard models. For instance, on the KITTI dataset, the SimVP-gSTA model achieves an MSE of approximately 145, while the SimVP-gSTA-L model's MSE is around 274.

Given these observations, I'm seeking advice or suggestions on how to optimize or improve the performance of the larger versions of these models. Any insights or guidance would be greatly appreciated.

Thank you for your assistance.

Thanks
Yang

**Comment by chengtan9907** [comment]
Yes... I also found that large models suffered from overfitting. I would suggest you train a small model for more epochs, which I found usually better than large models trained with almost the same gpu hours.

You may refer to our previous work: https://arxiv.org/abs/2211.12509.

**Comment by YangLi309** [comment]
Thanks for answering. I'll close this issue.
