### ISSUE TITLE
For Lightning Version, train.sh/test.sh is not provided.

### ISSUE THREAD

**Issue by yyyujintang** [chengtan9907/OpenSTL#95]
For the updated Lightning Version, the old version's script for DDP training is not matched anymore.
Could please provide the latest train.sh/test.sh for DDP training and test?

**Comment by chengtan9907** [comment]
Thank you for your comment. We are sorry for the confusion. In the Lightning version, to conduct multi-GPU experiments, you can execute the command `python tool/train.py --gpus 0 1`. For single GPU experiments, use `python tool/train.py --gpus 0`.

We will refine the readme and document to provide a more comprehensive and clearer guide.

**Comment by yyyujintang** [comment]
Thank you! Now I can use it.

**Comment by chengtan9907** [comment]
I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.
