### ISSUE TITLE
如何选择hid_S,hid_T,N_S,N_T的大小

### ISSUE THREAD

**Issue by xualiencd** [chengtan9907/OpenSTL#96]
你好，请问如何根据自己的数据集选择合适的hid_S,hid_T,N_S,N_T的大小？

**Comment by chengtan9907** [comment]
这取决于具体数据集是什么样的。我经验地认为，分辨率高的数据集需要取较大的N_S，例如4、8，因为更多的下采样可以使计算效率更高，相应地性能也会差一些；N_T默认用8或12就可以了；对于时空关系比较复杂的，hid_T可以取大一些，如256、512；hid_S仅影响空间的学习，不需要取很大。

**Comment by chengtan9907** [comment]
I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.
