### ISSUE TITLE
Data standardization for Human3.6M

### ISSUE THREAD

**Issue by YingtianDt** [chengtan9907/OpenSTL#97]
Hi, may I confirm that there is no standardization for the Human3.6M data? So the processing is basically just image values / 255.

Thanks!

**Comment by chengtan9907** [comment]
The value should be in [0,1]. I think no further standardization is needed.

**Comment by chengtan9907** [comment]
I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.
