### ISSUE TITLE
如何指定单个GPU进行训练

### ISSUE THREAD

**Issue by ZhangYuan1998** [chengtan9907/OpenSTL#98]
作者您好，感谢您开源的代码。
在此咨询一个问题，您的代码默认使用cuda:0的GPU，我如果想用cuda:3该如何更改。
此外，您提供了多个GPU训练的方法，但是好像并没有给予完整的文件如tools/dist_train.sh和tools/dist_test.sh。
期待您的回复！

**Comment by chengtan9907** [comment]
在现在的Lightning版本下，`python tools/train.py --gpus 3` 应该就可以了

**Comment by chengtan9907** [comment]
I will close this issue if there are no more questions. Please feel free to open a new issue when you have new questions.
